name = "Deploy App With GitHub Actions Tutorial"
description = "An app written for a tutorial about deploying apps with GitHub actions "
library = "streamlit"
python = "3.9"
app_file = "app.py"
requirements_file = "requirements.txt"
port = 80
cover_image = "app_cover.jpg"
exclude = ["*venv", "venv*", ".git", ".env"]
